// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA92CT6JFPf7V-MfKsi42Qdh07A8S9Mva8',
    appId: '1:102705479807:web:4f7f959b4923f0e163ff4a',
    messagingSenderId: '102705479807',
    projectId: 'recipe-app-f7f4c',
    authDomain: 'recipe-app-f7f4c.firebaseapp.com',
    databaseURL: 'https://recipe-app-f7f4c-default-rtdb.firebaseio.com',
    storageBucket: 'recipe-app-f7f4c.appspot.com',
    measurementId: 'G-PZ52GSPSP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuRSLlA8EuaJNAUtOf1PZY-CmyNDYGKEQ',
    appId: '1:102705479807:android:9115ae05b939278f63ff4a',
    messagingSenderId: '102705479807',
    projectId: 'recipe-app-f7f4c',
    databaseURL: 'https://recipe-app-f7f4c-default-rtdb.firebaseio.com',
    storageBucket: 'recipe-app-f7f4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqFRMGDsGUH_-dSNJrxrd1k3M4aBJfByw',
    appId: '1:102705479807:ios:286b1d7d64fcdf1d63ff4a',
    messagingSenderId: '102705479807',
    projectId: 'recipe-app-f7f4c',
    databaseURL: 'https://recipe-app-f7f4c-default-rtdb.firebaseio.com',
    storageBucket: 'recipe-app-f7f4c.appspot.com',
    iosClientId: '102705479807-1nk59bhcu5e2fm3kafs9s8odn3egomaf.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqFRMGDsGUH_-dSNJrxrd1k3M4aBJfByw',
    appId: '1:102705479807:ios:286b1d7d64fcdf1d63ff4a',
    messagingSenderId: '102705479807',
    projectId: 'recipe-app-f7f4c',
    databaseURL: 'https://recipe-app-f7f4c-default-rtdb.firebaseio.com',
    storageBucket: 'recipe-app-f7f4c.appspot.com',
    iosClientId: '102705479807-1nk59bhcu5e2fm3kafs9s8odn3egomaf.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstApp',
  );
}
